main: com.kolinkrewinkel.BitLimitTweaks.BitLimitTweaks
name: BitLimitTweaks
version: 1.4.5
author: Kolin Krewinkel
description: Code-level runtime tweaks for BitLimit Private Survival.
website: http://github.com/BitLimit/Tweaks/
commands:
    tweaks:
        description: Undefined
permissions:
    tweaks.*:
        description: Gives all permissions of BitLimit Tweaks plugin toggling.
        default: op