main: com.bitlimit.Tweaks.Tweaks
name: Tweaks
version: 1.5.0
author: Kolin Krewinkel & BitLimit Team
description: Code-level runtime tweaks for BitLimit Private Survival.
website: http://github.com/BitLimit/Tweaks/
commands:
    tweaks:
        description: /tweaks  [tnt|slimes|weather] [state] to set the state or omit the state to return the current config status.
permissions:
    tweaks.*:
        description: Gives all permissions of BitLimit Tweaks plugin toggling.
        default: op